const creativeProjectTags = [
  'digital-art',
  'illustration',
  'graphic-design',
  'photography',
  'videography',
  'animation',
  '3d-modeling',
  'web-design',
  'ui-ux',
  'branding',
  'logo-design',
  'packaging-design',
  'print-design',
  'motion-graphics',
  'concept-art',
  'character-design',
  'mixed-media',
  'installation-art',
  'interactive-art',
  'generative-art',
  'data-visualization',
  'virtual-reality',
  'augmented-reality',
  'game-design',
  'sound-design',
];

export default creativeProjectTags;
